inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**
    - config/**
    - script/**
  TargetRubyVersion: 2.5.0

StringLiterals:
  Enabled: false

LambdaCall:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/factories/**'
  ExcludedMethods:
    - attributes_table
    - register
    - controller
    - show
    - table_for
    - columns
    - column
    - feature
    - context
    - describe
    - it
    - scenario
    - shared_examples_for
    - form
    - inputs
    - shared_examples

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Naming/PredicateName:
  NamePrefixBlacklist:
    - is_

# Casecmp isn't particularly readable
Performance/Casecmp:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

# We don't consider .positive? etc to be that readable
Style/NumericPredicate:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/BlockEndNewline:
  Enabled: false

Layout/CaseIndentation:
  IndentOneStep: true

Layout/MultilineBlockLayout:
  Exclude:
    - 'test/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - delegate

Style/AsciiComments:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/AlignHash:
  EnforcedHashRocketStyle: table
