inherit_from:
  - .rubocop_todo.yml
  -
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DefaultFormatter: progress
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - db/schema.rb
    - vendor/**/*
    - bin/**/*
    - out/**/*

Bundler/OrderedGems:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

# Complexity
Metrics/ClassLength:
  Enabled: false
  CountComments: false
  Max: 200

Metrics/CyclomaticComplexity:
  Enabled: false
  Max: 20
  Exclude:
    - db/migrate/**/*

Layout/LineLength:
  Enabled: false
  Max: 300

Metrics/MethodLength:
  Enabled: false
  CountComments: false
  Max: 20
  Exclude:
    - db/migrate/**/*

Security/MarshalLoad:
  Enabled: false

Style/Alias:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - app/**/*
    - lib/**/*
    - db/**/*
    - config/**/*
    - Gemfile
    - Rakefile
    - config.ru
    - code_coverage.rb

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyLambdaParameter:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Include:
    - app/**/*
  IgnoredMethods:
    - require
    - require_relative
    - raise
    - render
    - link_to
    - redirect_to
    - redirect_back
    - return
    - stream_from
    - error
    - info
    - debug
    - yield
    - head
    - puts
    - send_file
    - redirect_post
    - send_data
    - mail

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - test/**/*

Lint/UnreachableCode:
  Exclude:
    - '*/**/concepts/**/operation/**/*'

Style/SignalException:
  Exclude:
    - '*/**/concepts/**/operation/**/*'
