default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: youinnumbers_development

test:
  <<: *default
  database: youinnumbers_test

production:
  <<: *default
  database: youinnumbers_production
