en:
  errors:
    user_exists?: "User not found"
    password_ok?: "Wrong Password"
    must_be_equal?: "Passwords are not matching"
    new_must_match?: "The New Password is not matching"
    new_password_must_be_new?: "New password can't match the old one"
    unique_email?: "This email has been already used"
    email?: "Wrong format"
    not_blocked?: "You have been blocked mate"
    at_least_one_file?: "At least one file must be uploaded"
    file_exists?: "The file selected doens't exist"
    greater_than_zero?: "This must be greater than zero"
    check_index?: "Operation not possible"
    check_age?: "Wrong age, Subject must be between 5 and 120 years old"
    unique_subject?: "Subject already present in the database"
    filled?: "Can't be blank"
    y1_scale: "Please show at least one Y scale"
    y2_scale: "Please show at least one Y scale"
    y3_scale: "Please show at least one Y scale"
